# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Drunkard's Walk
email: deanwong@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  这辈子最大的错误就是尝试在不确定的世界中寻找确定
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://drunkardwalk.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: deanwong
github_username:  dean-wong

lsi: false
permalink: /:title

# Build settings
markdown: kramdown
# Since GH pages override this to "true", we test this value to see if we are running locally
safe: false
include: [".well-known"]
# highlighter: none
# syntax_highlighter: none
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  # transliterated_header_ids: true
  syntax_highlighter_opts:
      disable: true
gems:
  - jekyll-redirect-from
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
